# Generated by Django 6.0.7 on 2026-07-17 19:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('letter_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('ns1', models.CharField(max_length=255)),
                ('ns2', models.CharField(max_length=255)),
                ('generated_letter', models.TextField()),
                ('emailed', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('citizenship_number', models.CharField(blank=True, max_length=100)),
                ('purpose', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('representative_name', models.CharField(blank=True, max_length=255)),
                ('company_registration_number', models.CharField(blank=True, max_length=255)),
                ('business_description', models.TextField(blank=True)),
            ],
        ),
    ]
