# Generated by Django 6.0.7 on 2026-07-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetterSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], max_length=10)),
                ('domain_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('citizenship_number', models.CharField(blank=True, max_length=50)),
                ('purpose', models.TextField(blank=True)),
                ('representative_name', models.CharField(blank=True, max_length=100)),
                ('representative_email', models.EmailField(blank=True, max_length=254)),
                ('representative_phone', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('company_registration_number', models.CharField(blank=True, max_length=100)),
                ('business_description', models.TextField(blank=True)),
                ('ns1', models.CharField(blank=True, max_length=100)),
                ('ns2', models.CharField(blank=True, max_length=100)),
                ('letter_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CoverLetter',
        ),
    ]
