# Generated by Django 6.0.7 on 2026-07-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coverlettersubmission_delete_coverletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='address',
        ),
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='citizenship_number',
        ),
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='company_registration_number',
        ),
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='letter_html',
        ),
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='ns1',
        ),
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='ns2',
        ),
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='representative_email',
        ),
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='representative_name',
        ),
        migrations.RemoveField(
            model_name='coverlettersubmission',
            name='representative_phone',
        ),
        migrations.AddField(
            model_name='coverlettersubmission',
            name='domain_tld',
            field=models.CharField(default='.com.np', max_length=2),
        ),
        migrations.AddField(
            model_name='coverlettersubmission',
            name='name',
            field=models.CharField(default='bisup', max_length=150),
        ),
        migrations.AlterField(
            model_name='coverlettersubmission',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
