# Generated by Django 6.0.7 on 2026-07-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_coverlettersubmission_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverlettersubmission',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
